language: ruby
sudo: false

rvm: 2.3

gemfile:
  - gemfiles/Gemfile.activerecord-4.1
  - gemfiles/Gemfile.activerecord-4.2
  - gemfiles/Gemfile.activerecord-5.1
  - gemfiles/Gemfile.activerecord-5.2
  - gemfiles/Gemfile.activerecord-6.1

env:
  - DB_ADAPTER=sqlite3
  - DB_ADAPTER=mysql2
  - DB_ADAPTER=postgresql

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - mysql -e 'create database microscope_test;'
  - psql -c 'create database microscope_test;' -U postgres

script:
  - 'echo "Checking code style" && bundle exec phare'
  - 'echo "Running tests" && bundle exec rake spec'
